version: "3.6"

services:
  watch_tower:
    image: atomex-protocol/watch_tower:${TAG:-latest}
    build:
        dockerfile: build/Dockerfile
        context: .
        args:
          - config_file=config.yml
    restart: always
    env_file: .env
