version: "3.6"

services:
  watch_tower:
    image: atomex-protocol/watch_tower:${TAG:-latest}
    build:
        dockerfile: build/watch_tower/Dockerfile
        context: .
        env:
          AP_ENV=production
    restart: always
    env_file: .env
  market_maker:
    image: atomex-protocol/market_maker:${TAG:-latest}
    build:
        dockerfile: build/market_maker/Dockerfile
        context: .
        env:
          AP_ENV=production
    restart: always
    env_file: .env
