KT1VG2WtYdSWz5E7chTeAdDPZNy2MpP8pTfL:
  gas_limit:
    initiate: "4000"
    redeem: "7000"
    refund: "7000"
  storage_limit:
    initiate: "257"
    redeem: "257"
    refund: "257"
  fee:
    initiate: "1000"
    redeem: "3000"
    refund: "10000"
KT1EpQVwqLGSH7vMCWKJnq6Uxi851sEDbhWL:
  gas_limit:
    initiate: "4000"
    redeem: "7000"
    refund: "7000"
  storage_limit:
    initiate: "257"
    redeem: "257"
    refund: "257"
  fee:
    initiate: "1000"
    redeem: "3000"
    refund: "10000"
KT1Ap287P1NzsnToSJdA4aqSNjPomRaHBZSr:
  gas_limit:
    initiate: "4000"
    redeem: "7000"
    refund: "7000"
  storage_limit:
    initiate: "257"
    redeem: "257"
    refund: "257"
  fee:
    initiate: "1000"
    redeem: "3000"
    refund: "10000"